services:
  ntfy-fetch:
    build: .
    container_name: ntfy-fetch
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=Pacific/Rarotonga
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./plugins:/app/plugins