services:
  ntfy-fetch:
    image: ghcr.io/mossly/ntfy-fetch:latest
    container_name: ntfy-fetch
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=${TZ:-Pacific/Rarotonga}
      - USE_EVENT_SCHEDULER=${USE_EVENT_SCHEDULER:-true}
      - WEBUI=${WEBUI:-true}
      - WEBUI_PORT=${WEBUI_PORT:-3000}
    ports:
      - "${HOST_PORT:-3033}:${WEBUI_PORT:-3000}"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      # Homepage dashboard integration
      - "homepage.group=Notifications"
      - "homepage.name=ntfy-fetch"
      - "homepage.icon=ntfy.png"
      - "homepage.href=http://${HOST_IP:-localhost}:${HOST_PORT:-3033}/ui"
      - "homepage.description=Extensible notification service with tide alerts"
      - "homepage.widget.type=customapi"
      - "homepage.widget.url=http://ntfy-fetch:${WEBUI_PORT:-3000}/api/snapshot"
      - "homepage.widget.mappings.0.label=Uptime"
      - "homepage.widget.mappings.0.field=system.uptimeSec"
      - "homepage.widget.mappings.0.format=duration"
      - "homepage.widget.mappings.1.label=Scheduler"
      - "homepage.widget.mappings.1.field=system.schedulerState"
      - "homepage.widget.mappings.2.label=Plugins"
      - "homepage.widget.mappings.2.field=system.taskCount"
      - "homepage.widget.mappings.2.suffix= tasks"