version: '3.8'

services:
  ntfy-fetch:
    build: .
    image: ntfy-fetch:latest
    container_name: ntfy-fetch
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./plugins:/app/plugins
    environment:
      - TZ=Pacific/Rarotonga
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=300  # Check every 5 minutes
      - WATCHTOWER_LABEL_ENABLE=true  # Only update containers with the label
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=generic+http://ntfy.mossly.org/watchtower?title=Watchtower&priority=low
    command: --interval 300 --cleanup --label-enable